# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e46fe8dc168136414d568725078f2204fc1df540fb2eb96a5e7dbe912623b2c22610f79edcea73cf26c30a78b0fe71c309bbb77d9974c71891557280e15dc193

test:
  secret_key_base: ceaed8ecc55b824ad0e03fe73709e7809821f2ba2883f3e74d568ca589dc71b4710dffc8b2edc972e25854596fb7448183da8327665494136a412b747763c00d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
